#!/bin/perl
use strict;
use warnings;

my ($URL, $DIRECTORY) = @ARGV;

if (not defined $URL) {
  die "PLEASE SPECIFY REMOTE URL";
}

if (not defined $DIRECTORY) {
  $DIRECTORY = "/";
}

my $CMD = "cd $DIRECTORY;". 
"mkdir .git;".
"git init;".
"git config --global --add safe.directory $DIRECTORY;".
"git remote add origin $URL;".
"git fetch;".
"git reset --hard origin/main;".
"git branch -m main;".
"chgrp -R git .git;".
"chmod -R g+w .git;".
"./scripts/git_misc/git_group_add";

system($CMD) == 0 or exit $?;
