#!/bin/perl
use strict;
use warnings;

my ($DIRECTORY) = @ARGV;

my $CMD = "";

if (defined $DIRECTORY) {
  $CMD = "cd $DIRECTORY;";
} 

my $GIT_TREE = "git ls-tree --full-tree --name-only -r HEAD";

$CMD .= "$GIT_TREE|xargs sudo chgrp git;".
  "$GIT_TREE|xargs sudo chmod g+w;".
  "$GIT_TREE|xargs sudo chmod g+x";

`$CMD`;
