#!/bin/perl
use strict;
use warnings;

my ($DIRECTORY) = @ARGV;

my $error_code = 0;

if (not defined $DIRECTORY) {
	$DIRECTORY = "/";
}
my $cmd = "cd $DIRECTORY; \\\n";

my $GIT_TREE = `git ls-tree --full-tree --name-only -r HEAD`;
my @FILES = split(/\n/, $GIT_TREE); # split result by line...
foreach (@FILES) {
	$cmd .= "sudo chgrp git $_; \\\n".
		"sudo chmod g+w $_; \\\n".
		"sudo chmod g+x $_; \\\n";
}

$cmd .= "sudo chgrp git $DIRECTORY; \\\n".
	"sudo chmod g+w $DIRECTORY; \\\n".
	"sudo chmod g+x $DIRECTORY";
print("$cmd\n");
exit system($cmd);
