#!/bin/perl

my ($INTERFACE, $BRIDGE) = @ARGV;

system("ip tuntap add dev $INTERFACE mode tap");
system("ip link set dev $INTERFACE master $BRIDGE");
system("ip link set $INTERFACE up") == 0 or exit $?;
