#!/bin/sh

CMD_TUN_CREATE="ip tuntap add dev $1 mode tap"
CMD_LINK_BR="ip link set dev $1 master $2"
CMD_LINK_UP="ip link set $1 up"

echo $CMD_TUN_CREATE
echo $CMD_LINK_BR
echo $CMD_LINK_UP

exec $CMD_TUN_CREATE
exec $CMD_LINK_BR
exec $CMD_LINK_UP
