#!/bin/bash
export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
export LIBGL_DRIVERS_PATH=/usr/local/lib/x86_64-linux-gnu/dri
export LIBGL_DEBUG=verbose
export MESA_DEBUG=1
export DRI_PRIME="10de:13c2"
export LP_DEBUG=1
export LIBGL_ALWAYS_INDIRECT=0
export GALLIUM_PRINT_OPTIONS=1
export LIBGL_ALWAYS_SOFTWARE=0
export DRM_SHIM_DEBUG=1

echo "Configured env variables for open_gl debugging:"
printenv | grep -Pe "LD_LIBRARY_PATH|LIBGL_DRIVERS_PATH|LIBGL_DEBUG|MESA_DEBUG|DRI_PRIME|LP_DEBUG|LIBGL_ALWAYS_INDIRECT|GALLIUM_PRINT_OPTIONS|LIBGL_ALWAYS_SOFTWARE"
printenv | grep -Pe "DRM_SHIM_DEBUG"
