#!/bin/perl -I/scripts/perl_modules

use ArgParse;

# ArgParse_test -key value
# result:
# ArgParse_test -key value value
# result:
# ArgParse_test -key "value value"
# result: 

my %processors = {
	"-test" => {
		$ArgParse::SUB_KEY => sub {
			"sub" => sub {
				my ($val) = @_;
				print("PROCESSING -test with value $val\n");
			},
			#	$ArgParse::USAGE_KEY => "TEST ARGUMENT",
		"usage" => "TEST ARGUMENT"
	}
}
};

#ArgParse::addProcessors(\%processors);
ArgParse::parse();
ArgParse::processAll();
