#!/bin/bash

# initialize taptun interface
tap-ifup tap0 br0

qemu-system-x86_64 \
	-enable-kvm \
	-cpu host \
	-m 16G \
	-machine q35 \
	-name "Windows10" \
	-smp cores=2 \
	-device virtio-vga-gl \
	-display sdl,gl=on \
	-monitor stdio \
	-netdev tap,id=nd0,ifname=tap0,script=no,downscript=no \
	-device e1000,netdev=nd0 \
	-boot order=c,menu=on,strict=on \
	-smbios type=0,uefi=on \
	-device vfio-pci,host=01:00.0 \
	-device vfio-pci,host=01:00.1 \
	-drive file=/dev/sda,index=0,media=disk,if=ide,cache=writeback,aio=threads,format=raw \
	-usb \
	-device usb-host,vendorid=0x045e,productid=0x02dd \
	-device usb-host,vendorid=0x2357,productid=0x0120 \
	$@

	#-usb
	#-drive file=/dev/sda,index=0,media=disk,if=ide,cache=writeback,aio=threads,format=raw \
	# -display sdl,gl=on \
	#-vga virtio \
	#-nic bridge,br=virbr0,mac=f6:96:5b:61:84:23 \
	#-net nic,model=e1000 \
	#-net bridge,br=virbr0,mac=f6:96:5b:61:84:23 \
	#-cdrom /home/floxnard7/Downloads/Win10_22H2_English_x64v1.iso \
	#-bios /usr/share/edk2/x64/OVMF.fd \
	#
	#-hda /dev/sda \
	#-hda /dev/sda1 \
	#-hdb /dev/sda2 \
	#-hdc /dev/sda3 \
	#-hdd /dev/sda4 \
#
	#-drive file=/dev/sda4,index=1,media=disk,if=ide,cache=writeback,aio=threads,format=raw \
	#
	#-blockdev driver=raw,node-name=disk_boot,file=/dev/sda1 \
	#-drive file=/dev/sda1,index=0,media=disk,format=raw,node-name=disk_boot,if=scsi\
	#-blockdev driver=raw,node-name=disk_boot,file=/dev/sda2 \
	#-drive file=/dev/sda2,index=0,media=disk,format=raw,node-name=disk_boot,if=scsi \
	#-blockdev driver=raw,node-name=disk_device,file=/dev/sda3 \
	#-drive file=/dev/sda3,index=0,media=disk,format=raw,node-name=disk_boot,if=scsi \
	#-blockdev driver=raw,node-name=disk_device,file=/dev/sda4 \
	#-drive file=/dev/sda4,index=0,media=disk,format=raw,node-name=disk_boot,if=scsi \
#
	#-drive file=/dev/sda1,index=0,media=disk,if=scsi \
	#-drive file=/dev/sda2,index=1,media=disk,if=scsi \
	#-drive file=/dev/sda3,index=2,media=disk,if=scsi \
	#-drive file=/dev/sda4,index=3,media=disk,if=scsi \
