#!/bin/perl

# initialize taptun interface
`tap-ifup tap1 br0`;

#foreach (@ARGV) {
#	print("$_\n");
#}

my $CMD = "qemu-system-x86_64 \\\n".
	"\t-enable-kvm \\\n".
	"\t-cpu host \\\n".
	"\t-m 16G \\\n".
	"\t-machine q35 \\\n".
	"\t-name \"Ubuntu\" \\\n".
	"\t-smp cores=2 \\\n".
	"\t-boot order=c,menu=on,strict=on \\\n".
	"\t-vga virtio \\\n".
	"\t-netdev tap,id=nd0,ifname=tap1,script=no,downscript=no \\\n".
	"\t-device e1000,netdev=nd0 \\\n".
	"\t-drive file=ubuntu.cow,format=qcow2 \\\n";

if ($ARGV[0] == "-v") {
	$CMD.="\t-device vfio-pci,host=01:00.0 \\\n".
	"\t-device vfio-pci,host=01:00.1 \\\n". 
	"\t".join(" ",@ARGV[1..$#ARGV]);
} else {
	$CMD.="\t".join(" ",@ARGV);
}

print("Launching: \n");
print("$CMD\n");
exec $CMD;
