#!/bin/bash

# initialize taptun interface
tap-ifup tap0 br0

CMD="qemu-system-x86_64 
	-enable-kvm 
	-cpu host 
	-m 16G 
	-machine q35 
	-name \"Windows10\" 
	-smp cores=2 
	-boot order=c,menu=on,strict=on 
	-smbios type=0,uefi=on 
	-device virtio-vga-gl 
	-netdev tap,id=nd0,ifname=tap0,script=no,downscript=no 
	-device e1000,netdev=nd0 
	-drive file=/dev/sda,index=0,media=disk,if=ide,cache=writeback,aio=threads,format=raw 
	-usb 
	-device usb-host,vendorid=0x045e,productid=0x02dd 
	"
	if [ $1 -eq "-v" ]; then
		CMD=$CMD"-device vfio-pci,host=01:00.0
		-device vfio-pci,host=01:00.1
		"
		${@:2} # skip first argument during expansion
	else
		CMD=$CMD$@
	fi

echo "Launching: "
echo -e "$CMD"
exec $CMD
