#!/bin/bash

# initialize taptun interface
tap-ifup tap1 br0

CMD="qemu-system-x86_64
	-enable-kvm 
	-cpu host 
	-m 16G 
	-machine q35 
	-name \"Ubuntu\" 
	-smp cores=2 
	-boot order=c,menu=on,strict=on 
	-vga virtio 
	-netdev tap,id=nd0,ifname=tap1,script=no,downscript=no 
	-device e1000,netdev=nd0 
	-drive file=ubuntu.cow,format=qcow2 
	"
    if [ $1 -eq "-v" ]; then 
		CMD=$CMD"-device vfio-pci,host=01:00.0 
		-device vfio-pci,host=01:00.1 
		"
		${@:2} # skip first argument during expansion
	else 
		CMD=$CMD$@
    fi
echo "Launching: "
echo -e "$CMD"
exec $CMD
