#!/bin/perl

use strict;
use warnings;

my ($SWITCH) = @ARGV;

my $DEVICE_ID_VIDEO = "0000:01:00.0"; # video
my $DEVICE_ID_VIDEO_AUDIO = "0000:01:00.1"; # audio

my $VFIO_DRIVER_NAME = "vfio-pci";
my $VIDEO_DRIVER_NAME = "nvidia";
my $AUDIO_DRIVER_NAME = "snd_hda_intel";

sub printDriverState {
	print("Driver State: \n\n");

	print("VFIO driver: \n");
	system("ls -la /sys/bus/pci/drivers/$VFIO_DRIVER_NAME");
	print("\nVideo driver: \n");
	system("ls -la /sys/bus/pci/drivers/$VIDEO_DRIVER_NAME");
	print("\nAudio driver: \n");
	system("ls -la /sys/bus/pci/drivers/$AUDIO_DRIVER_NAME");
}

sub executeCmd {
	my $cmd = shift;
	print("$cmd\n");
	system($cmd);
}

sub updateDeviceToDriverLinkState {
	my ($device_id, $driver_name, $bind_state) = @_;
	executeCmd("echo $device_id > /sys/bus/pci/drivers/$driver_name/$bind_state");
}

sub bindVideoOrLoadDriver {
	# hash map of arrays since we are being explicit
	my %driver_names = (
		"vfio-pci" => ("vfio_pci", "vfio_iommu_type1", "vfio"),
		"nvidia" => ("nvidia_uvm", "nvidia_drm", "nvidia_modeset", "nvidia")
	);
	my $driver_name = shift;
	foreach($driver_names{$driver_name}) {
		if (`lsmod` =~ /$_/) { # TODO: inverse match?
		} else {
			executeCmd("modprobe $_");
			if (`lsmod` =~ /$_/) {
				if ($driver_name ne "vfio_pci") {
					print("ATTENTION! $driver_name driver enabled... please restart the Display Manager?.\n");
				}
			} else {
				print("Failed to load $_ module.");
			}
		}
	} 
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO, $driver_name, "bind");
}

print("Configuring drivers... \n");
if ($SWITCH eq "-off") {
	# unbind vfio video driver
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO, $VFIO_DRIVER_NAME, "unbind");

	# unbind vfio audio driver
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO_AUDIO, $VFIO_DRIVER_NAME, "unbind");

	# bind snd_hda_intel audio driver
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO_AUDIO, $AUDIO_DRIVER_NAME, "bind");

	# bind video driver
	bindVideoOrLoadDriver($VIDEO_DRIVER_NAME);

	print("Toggled $DEVICE_ID_VIDEO to $VIDEO_DRIVER_NAME\n");
	print("Toggled $DEVICE_ID_VIDEO_AUDIO to $AUDIO_DRIVER_NAME\n\n");
	print("See warning/error messages above.\n");
} elsif ($SWITCH eq "-on") {
	# unbind video driver
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO, $VIDEO_DRIVER_NAME, "unbind");

	# unbind snd_hda_intel audio driver
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO_AUDIO, $AUDIO_DRIVER_NAME, "unbind");

	# bind VFIO audio
	updateDeviceToDriverLinkState($DEVICE_ID_VIDEO_AUDIO, $VFIO_DRIVER_NAME, "bind");

	# bind VFIO video
	bindVideoOrLoadDriver($VFIO_DRIVER_NAME);
	
	print("Toggled $DEVICE_ID_VIDEO to $VFIO_DRIVER_NAME\n");
	print("Toggled $DEVICE_ID_VIDEO_AUDIO to $VFIO_DRIVER_NAME\n\n");
	print("See warning/error messages above.\n");
} else {
	print("User did not provide any valid options, printing current state: \n\n");
}

printDriverState();
