#
# More function keys and console assignments
# These are not in the main map in order to save keymaps
# Load after the main keymap, or include in the main keymap.
#
#keymaps 5,9
# no focus

control keycode 28 = Insert
shift control keycode 2 = F1
shift control keycode 3 = F2
shift control keycode 4 = F3
shift control keycode 5 = F4
shift control keycode 6 = F5
shift control keycode 7 = F6
shift control keycode 8 = F7
#alt Backspace = Delete
control keycode  41 = Escape
control keycode  103 = PageUp 
control keycode  106 = End
control keycode  105 = Home
control keycode  108 = PageDown

#keycode 464 keycode 41 = Escape
