#!/bin/python3

import subprocess
import os

# Would like this to be a static config file thing but this works for now....

# assume UTF-8 for now..
ms = subprocess.check_output(['xrandr', '--listactivemonitors']).decode("utf-8")

displays = {}
for line in ms.split(os.linesep):
    display = [x for x in line.strip().split(" ") if x != ""]
    if len(display) == 4:
        print(display)
        displays[display[3]] = display[2]

print(displays)
for display_name, resolution in displays.items():
    ms = subprocess.check_output(['xrandr', '--listactivemonitors']).decode("utf-8")
    if resolution.startswith("2560"):
        os.system(f"xrandr --output {display_name} --rotate right --primary")
#	elif resolution.startswith("5120"):
#		os.system(f"xrandr --output {display_name} --primary")
